spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/ws?characterEncoding=utf8&useSSL=false
    username: root
    password: Yun123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    format_sql: true
server:
  port: 7101
  name: imservice
  tomcat:
    uri-encoding: UTF-8
    max-threads: 10000
    max-connections: 10000

task:
  removeDataDay: 7
  removeCashHour: 24

snowflakeidworker:
  workerid: 0
  datacenterid: 1

logging:
  level:
    root: info
